site_name: Documentação Concreto Armado
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top

nav:
  - Aulas Concreto II:
      - "Aula 1 - Pilares de Concreto Armado: Dimensionamento": aula1.md
      - "Aula 2 - Dimensionamento de Pilares: Cargas Axiais e Flexão": aula2.md
      - "Aula 3 - Pilares com Excentricidade": aula3.md
      - "Aula 4 - Pilares Curvos": aula4.md
      - "Aula 5 - Análise de Pórticos: Métodos de Cálculo": aula5.md
      - "Aula 6 - Dimensionamento de Pórticos: Cargas Estáticas": aula6.md
      - "Aula 7 - Dimensionamento de Pórticos: Cargas Dinâmicas": aula7.md
      - "Aula 8 - Cargas Dinâmicas: Impacto e Vibração": aula8.md
      - "Aula 9 - Projeto de Pilares e Pórticos: Considerações Práticas": aula9.md
      - "Aula 10 - Estudos de Caso e Aplicações Reais": aula10.md
  - Introdução:
      - "O que é Concreto Armado?": index.md
      - "História e Evolução": historia.md
      - "Vantagens e Desvantagens": vantagens_desvantagens.md
  - Materiais:
      - Cimento:
          - "Tipos de Cimento": cimento_tipos.md
          - "Propriedades do Cimento": cimento_propriedades.md
      - Agregados:
          - "Tipos de Agregados": agregados_tipos.md
          - "Granulometria": agregados_granulometria.md
      - Água: agua.md
      - Aditivos: aditivos.md
      - Aço:
          - "Tipos de Aço": aco_tipos.md
          - "Armaduras": aco_armaduras.md
  - Projeto Estrutural:
      - "Normas Técnicas": normas.md
      - "Elementos Estruturais":
          - Lajes: lajes.md
          - Vigas: vigas.md
          - Pilares: pilares.md
          - Fundações: fundacoes.md
      - "Estados Limites": estados_limites.md
  - Execução:
      - "Preparo do Concreto": preparo_concreto.md
      - "Lançamento e Adensamento": lancamento_adensamento.md
      - "Cura do Concreto": cura.md
      - "Formas e Escoramentos": formas_escoramentos.md
  - Patologias:
      - "Fissuras": fissuras.md
      - "Corrosão": corrosao.md
      - "Outros Problemas": outros_problemas.md
  - Manutenção: manutencao.md
  - Referências: referencias.md
