site_name: Documentação Concreto Armado
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top

nav:
  - Ftools: "https://drive.google.com/drive/folders/1E4grQgWfzBDn0W1CbF6h18pv5_oDq2v4?usp=sharing"
  - Aulas Concreto II:
      - "Aula 1 - Introdução e Direcionamentos Iniciais": aula1.md
      - "Aula 2 - Conceitos Fundamentais sobre Pilares": aula2.md
      - "Aula 3 - Atividade de Croqui (Dimensionamento do Pórtico Inicial)": aula3.md
      - "Aula 4 - Dimensionamento de pilares": aula4.md
    #   - "Aula 5 - Cálculo de Reações de Apoio do Pórtico": aula5.md
    #   - "Aula 6 - Diagrama dos Esforços Normal e Cortante": aula6.md
    #   - "Aula 7 - Diagrama de Momento Fletor (parte1)": aula7.md
    #   - "Aula 8 - Diagrama de Momento Fletor (parte2)": aula8.md
    #   - "Aula 9 - Considerações Práticas": aula9.md
    #   - "Aula 10 - Estudos de Caso e Aplicações Reais": aula10.md
  - Introdução:
      - "O que é Concreto Armado?": index.md
      - "História e Evolução": historia.md
      - "Vantagens e Desvantagens": vantagens_desvantagens.md
  - Materiais:
      - Cimento:
          - "Tipos de Cimento": cimento_tipos.md
          - "Propriedades do Cimento": cimento_propriedades.md
      - Agregados:
          - "Tipos de Agregados": agregados_tipos.md
          - "Granulometria": agregados_granulometria.md
      - Água: agua.md
      - Aditivos: aditivos.md
      - Aço:
          - "Tipos de Aço": aco_tipos.md
          - "Armaduras": aco_armaduras.md
  - Projeto Estrutural:
      - "Normas Técnicas": normas.md
      - "Elementos Estruturais":
          - Lajes: lajes.md
          - Vigas: vigas.md
          - Pilares: pilares.md
          - Fundações: fundacoes.md
      - "Estados Limites": estados_limites.md
  - Execução:
      - "Preparo do Concreto": preparo_concreto.md
      - "Lançamento e Adensamento": lancamento_adensamento.md
      - "Cura do Concreto": cura.md
      - "Formas e Escoramentos": formas_escoramentos.md
  - Patologias:
      - "Fissuras": fissuras.md
      - "Corrosão": corrosao.md
      - "Outros Problemas": outros_problemas.md
  - Manutenção: manutencao.md
  - Referências: referencias.md


markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.2.0/es5/tex-mml-chtml.js